name: theooriginplugin
version: 1.0
author: TheoOrigin
main: fr.theoorigin.baseplugin.Main
commands:
  discord:
    description: discord link
    permission: discord.use
  alert:
    description: server alert
    permission: serveralert.use